# 1. Push Protection を有効化
# 2. security-check.yml を追加
# 3. Checkov を回す

# やる順番
# 1. Security チェックを CI に追加
# 2. Terraform の state を S3 backend に移す
# 3. module を 1つ切り出す
# 4. dev / prod を分ける

name: Security Check

on:
  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/security-check.yml"

jobs:
  checkov:
    name: Checkov Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform